### ISSUE TITLE
Feature Request: ATS support

### ISSUE THREAD

**Issue by ghost** [ets666/ets666-tool#2]
Hi,

Is it possible to make this tool compatible with ATS as well?

**Comment by sunwinbus** [comment]
Hi, @therealabradolf 
We are considering adding support for ATS (save editing only), but the release date is unsure.
Currently, you could open `%AppData%\ets666\data.json` and change `path` into ATS one if you want to edit save files of ATS.

**Comment by sunwinbus** [comment]
Support for ATS since v0.1.1
