### ISSUE TITLE
Unlock skill menu

### ISSUE THREAD

**Issue by Nixumuil** [ets666/ets666-tool#5]
已知:仅当游戏等级从0级升级到1级的时候，【技能】按钮才会同步解锁.
问题:当游戏等级不满1级时，使用ETS666改[等级]将永远错过解锁【技能】按钮的机会。>1级即可避免此问题。
附加效果:可在线买车

未修改前
![image](https://github.com/ets666/ets666-tool/assets/86508581/04a63482-e499-4abb-8e71-88bb6265bd34)
![image](https://github.com/ets666/ets666-tool/assets/86508581/76b410d3-5906-47dd-aa8b-24525d6e0381)

修改后
![image](https://github.com/ets666/ets666-tool/assets/86508581/ead2c411-ac90-4ba1-9588-57dfaa444995)
![image](https://github.com/ets666/ets666-tool/assets/86508581/29d3a245-e3f1-41c2-b2e4-6c472d929392)
————————————————————————————

预期:解锁等级或技能的同时，同步解锁全部菜单
(清空screen_access_list列表，改0)

**Comment by sunwinbus** [comment]
Fixed [449ef79](https://github.com/ets666/ets666-tool/commit/449ef79764091f8b653c5ba5287595f95913066a)
