### ISSUE TITLE
Feature Request: Added the ability to unlock all driver showers

### ISSUE THREAD

**Issue by WangSimele** [ets666/ets666-tool#6]

**Comment by sunwinbus** [comment]
> _No description provided._

Could you please describe what *driver showers* is?

**Comment by WangSimele** [comment]
> > _未提供说明。_
> 
> 您能描述一下_什么是驾驶员淋浴器_吗？

Places to hire drivers in the game.

**Comment by sunwinbus** [comment]
We have no plan to add this function currently
